// ─── GÉNÉRÉ depuis backend/app/models/all_models.py (SQLAlchemy → dialecte SQLite) ───
// Ne pas éditer à la main : régénérer si le schéma backend change (voir wiki features/mobile-standalone).

export const SCHEMA_VERSION = 1

export const SCHEMA_STATEMENTS: string[] = [
`CREATE TABLE "AppSettings" (
	id INTEGER NOT NULL, 
	cle VARCHAR(100) NOT NULL, 
	valeur VARCHAR(500), 
	label VARCHAR(200), 
	PRIMARY KEY (id), 
	UNIQUE (cle)
)`,
`CREATE TABLE "Breeder" (
	id_breeder INTEGER NOT NULL, 
	nom_breeder VARCHAR(255) NOT NULL, 
	origine_breeder VARCHAR(255), 
	information_breeder VARCHAR(255), 
	PRIMARY KEY (id_breeder)
)`,
`CREATE TABLE "Fournisseur" (
	id_fournisseur INTEGER NOT NULL, 
	nom_fournisseur VARCHAR(255) NOT NULL, 
	site_web VARCHAR(255), 
	PRIMARY KEY (id_fournisseur)
)`,
`CREATE TABLE "Marque" (
	id_marque INTEGER NOT NULL, 
	nom_marque VARCHAR(50), 
	siteweb_marque VARCHAR(100), 
	contact_marque VARCHAR(100), 
	PRIMARY KEY (id_marque)
)`,
`CREATE TABLE "Materiel" (
	id_materiel INTEGER NOT NULL, 
	categorie VARCHAR(50) NOT NULL, 
	nom VARCHAR(200) NOT NULL, 
	marque VARCHAR(100), 
	code_barre_serial VARCHAR(100), 
	date_achat DATE, 
	prix_achat DECIMAL(10, 2), 
	site_achat VARCHAR(200), 
	etat VARCHAR(50), 
	date_sortie_stock DATE, 
	notes TEXT, 
	caracteristiques JSON, 
	PRIMARY KEY (id_materiel)
)`,
`CREATE TABLE "NotationVariete" (
	id_notation INTEGER NOT NULL, 
	nom_variete VARCHAR(255) NOT NULL, 
	breeder VARCHAR(255), 
	date_notation DATE NOT NULL, 
	vigueur_sante FLOAT, 
	productivite_structure FLOAT, 
	soif FLOAT, 
	apparence_structure FLOAT, 
	profil_aromatique FLOAT, 
	saveur_qualite FLOAT, 
	effet_puissance FLOAT, 
	taux_thc FLOAT, 
	taux_cbd FLOAT, 
	terpene_dominant VARCHAR(500), 
	commentaire_labo TEXT, 
	notes_generales TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id_notation)
)`,
`CREATE TABLE "ParametreListeValeur" (
	id_parametre INTEGER NOT NULL, 
	liste_nom VARCHAR(100) NOT NULL, 
	valeur VARCHAR(500) NOT NULL, 
	ordre INTEGER, 
	PRIMARY KEY (id_parametre)
)`,
`CREATE TABLE "ProduitEngrais" (
	id_produit INTEGER NOT NULL, 
	nom_produit VARCHAR(200) NOT NULL, 
	marque VARCHAR(100), 
	type_produit VARCHAR(50), 
	conditionnement VARCHAR(50), 
	volume_conditionnement DECIMAL(10, 3), 
	unite_volume VARCHAR(10), 
	prix_achat DECIMAL(10, 2), 
	date_achat DATE, 
	date_peremption DATE, 
	quantite_stock DECIMAL(10, 3), 
	unite_quantite VARCHAR(10), 
	dosage_conseille VARCHAR(500), 
	notes TEXT, 
	PRIMARY KEY (id_produit)
)`,
`CREATE TABLE "RecetteArrosage" (
	id_recette_arrosage INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	type_arrosage VARCHAR(50), 
	quantite_eau FLOAT, 
	unite_eau VARCHAR(10), 
	notes TEXT, 
	PRIMARY KEY (id_recette_arrosage)
)`,
`CREATE TABLE "RecetteEngrais" (
	id_recette INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	type_recette VARCHAR(50), 
	periode VARCHAR(50), 
	semaine INTEGER, 
	ph_cible FLOAT, 
	notes TEXT, 
	PRIMARY KEY (id_recette)
)`,
`CREATE TABLE "RecetteFermentation" (
	id_recette_ferm INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	type_fermentation VARCHAR(50), 
	volume_total FLOAT, 
	unite_volume VARCHAR(10), 
	duree_fermentation INTEGER, 
	notes TEXT, 
	PRIMARY KEY (id_recette_ferm)
)`,
`CREATE TABLE "RecetteLSO" (
	id_recette_lso INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	type_lso VARCHAR(50), 
	quantite_totale FLOAT, 
	unite_quantite VARCHAR(10), 
	notes TEXT, 
	PRIMARY KEY (id_recette_lso)
)`,
`CREATE TABLE "RecetteReamendement" (
	id_recette_reamend INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	volume_pot FLOAT, 
	unite_pot VARCHAR(10), 
	notes TEXT, 
	PRIMARY KEY (id_recette_reamend)
)`,
`CREATE TABLE "RecetteTCO" (
	id_recette_tco INTEGER NOT NULL, 
	nom_recette VARCHAR(200) NOT NULL, 
	type_tco VARCHAR(50), 
	quantite_tco FLOAT, 
	unite_tco VARCHAR(10), 
	duree_oxygenation_h INTEGER, 
	notes TEXT, 
	PRIMARY KEY (id_recette_tco)
)`,
`CREATE TABLE "StockAlertSeuil" (
	type_stock VARCHAR(50) NOT NULL, 
	seuil_bocal_g DECIMAL(10, 2), 
	seuil_bocal_pct DECIMAL(5, 1), 
	seuil_total_g DECIMAL(10, 2), 
	actif BOOLEAN NOT NULL, 
	PRIMARY KEY (type_stock)
)`,
`CREATE TABLE "Vaporisateur" (
	id_vaporisateur INTEGER NOT NULL, 
	nom VARCHAR(200) NOT NULL, 
	modele VARCHAR(100), 
	marque VARCHAR(100), 
	site_achat VARCHAR(200), 
	date_achat DATE, 
	prix_achat DECIMAL(10, 2), 
	numero_serie VARCHAR(100), 
	type_chauffe VARCHAR(50), 
	a_eau BOOLEAN, 
	temp_min INTEGER, 
	temp_max INTEGER, 
	compatibilites VARCHAR(200), 
	type_batterie VARCHAR(50), 
	autonomie_sessions INTEGER, 
	autonomie_mah INTEGER, 
	temps_chauffe_s INTEGER, 
	type_charge VARCHAR(50), 
	nbr_sessions INTEGER, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_vaporisateur)
)`,
`CREATE TABLE "Variete" (
	id_variete INTEGER NOT NULL, 
	nom_variete VARCHAR(255) NOT NULL, 
	croisement_variete VARCHAR(255), 
	informations_variete VARCHAR(255), 
	lien_web VARCHAR(500), 
	PRIMARY KEY (id_variete)
)`,
`CREATE TABLE "AchatEngrais" (
	id_achat INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	date_achat DATE, 
	volume_achat DECIMAL(10, 3), 
	unite_volume VARCHAR(10), 
	prix_achat DECIMAL(10, 2), 
	date_peremption DATE, 
	conditionnement VARCHAR(50), 
	notes VARCHAR(500), 
	created_at DATETIME, 
	PRIMARY KEY (id_achat), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "Bocal" (
	id_bocal INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	taille_bocal INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	PRIMARY KEY (id_bocal), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "Box" (
	id_box INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	largeur_tente INTEGER, 
	profondeur_tente INTEGER, 
	hauteur_tente INTEGER, 
	nbr_etage INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	etat VARCHAR(50), 
	nbr_culture INTEGER, 
	PRIMARY KEY (id_box), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "Engrais" (
	id_engrais INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	nom_engrais VARCHAR(255), 
	quantite_bouteille DECIMAL(10, 2), 
	quantite_restante DECIMAL(10, 2), 
	unite_mesure VARCHAR(10), 
	prix_achat DECIMAL(10, 2), 
	date_achat DATE, 
	date_peremption DATE, 
	information_complementaire VARCHAR(255), 
	PRIMARY KEY (id_engrais), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "EspaceCulture" (
	id_espace INTEGER NOT NULL, 
	nom VARCHAR(200) NOT NULL, 
	type_espace VARCHAR(50), 
	id_materiel_principal INTEGER, 
	dimensions VARCHAR(100), 
	surface_m2 FLOAT, 
	hauteur_cm INTEGER, 
	statut VARCHAR(50), 
	notes TEXT, 
	PRIMARY KEY (id_espace), 
	FOREIGN KEY(id_materiel_principal) REFERENCES "Materiel" (id_materiel)
)`,
`CREATE TABLE "IceOBag" (
	id_iceobag INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	maillage_iceobag VARCHAR(50), 
	date_achat_iceobag DATE, 
	prix_iceobag DECIMAL(10, 2), 
	info_iceobag VARCHAR(100), 
	PRIMARY KEY (id_iceobag), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "Irrigation" (
	id_irrigation INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	type_irrigation VARCHAR(50), 
	debit_irrigation INTEGER, 
	diametre_irrigation INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	nbr_culture INTEGER, 
	PRIMARY KEY (id_irrigation), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "Lampe" (
	id_lampe INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	largeur_lampe INTEGER, 
	profondeur_lampe INTEGER, 
	hauteur_lampe INTEGER, 
	puissance_lampe INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	etat VARCHAR(50), 
	nbr_culture INTEGER, 
	PRIMARY KEY (id_lampe), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "PackGraine" (
	id_packgraine INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	nbr_graines INTEGER, 
	prix_achat DECIMAL(10, 2), 
	date_achat DATE, 
	duree_conservation_mois INTEGER, 
	PRIMARY KEY (id_packgraine), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur)
)`,
`CREATE TABLE "Pollen" (
	id_pollen INTEGER NOT NULL, 
	nom_pollen VARCHAR(255) NOT NULL, 
	id_variete_source INTEGER, 
	pheno_source VARCHAR(100), 
	reverse BOOLEAN, 
	date_collecte DATE, 
	quantite_initiale_g DECIMAL(6, 3), 
	quantite_restante_g DECIMAL(6, 3), 
	stockage VARCHAR(50), 
	date_peremption DATE, 
	actif BOOLEAN, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_pollen), 
	FOREIGN KEY(id_variete_source) REFERENCES "Variete" (id_variete)
)`,
`CREATE TABLE "Pot" (
	id_pot INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	taille_pot INTEGER, 
	dimension_pot VARCHAR(50), 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	etat VARCHAR(50), 
	nbr_culture INTEGER, 
	PRIMARY KEY (id_pot), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "PreparationSubstrat" (
	id_preparation INTEGER NOT NULL, 
	date_preparation DATE NOT NULL, 
	volume_total_l DECIMAL(8, 2) NOT NULL, 
	type_sol VARCHAR(100), 
	id_recette_lso INTEGER, 
	nom_recette_lso VARCHAR(200), 
	configuration_pots TEXT, 
	resultat TEXT, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_preparation), 
	FOREIGN KEY(id_recette_lso) REFERENCES "RecetteLSO" (id_recette_lso)
)`,
`CREATE TABLE "Press" (
	id_press INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	largeur_plate DECIMAL(10, 1), 
	profondeur_plate DECIMAL(10, 1), 
	pression_press INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	PRIMARY KEY (id_press), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "RecetteArrosageLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette_arrosage INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	quantite FLOAT NOT NULL, 
	unite VARCHAR(10), 
	note_ligne VARCHAR(500), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette_arrosage) REFERENCES "RecetteArrosage" (id_recette_arrosage), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RecetteEngraisLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	dosage FLOAT NOT NULL, 
	unite VARCHAR(10), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette) REFERENCES "RecetteEngrais" (id_recette), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RecetteFermentationLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette_ferm INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	quantite FLOAT NOT NULL, 
	unite VARCHAR(10), 
	note_ligne VARCHAR(500), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette_ferm) REFERENCES "RecetteFermentation" (id_recette_ferm), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RecetteLSOLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette_lso INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	quantite FLOAT NOT NULL, 
	unite VARCHAR(10), 
	note_ligne VARCHAR(500), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette_lso) REFERENCES "RecetteLSO" (id_recette_lso), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RecetteReamendementLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette_reamend INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	quantite FLOAT NOT NULL, 
	unite VARCHAR(10), 
	note_ligne VARCHAR(500), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette_reamend) REFERENCES "RecetteReamendement" (id_recette_reamend), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RecetteTCOLigne" (
	id_ligne INTEGER NOT NULL, 
	id_recette_tco INTEGER NOT NULL, 
	id_produit INTEGER NOT NULL, 
	quantite FLOAT NOT NULL, 
	unite VARCHAR(10), 
	note_ligne VARCHAR(500), 
	ordre INTEGER, 
	PRIMARY KEY (id_ligne), 
	FOREIGN KEY(id_recette_tco) REFERENCES "RecetteTCO" (id_recette_tco), 
	FOREIGN KEY(id_produit) REFERENCES "ProduitEngrais" (id_produit)
)`,
`CREATE TABLE "RosinBag" (
	id_rosinbag INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	dimensions_rosinbag VARCHAR(50), 
	maillage VARCHAR(50), 
	nombre_rosinbag VARCHAR(50), 
	date_achat_rosinbag DATE, 
	prix_rosinbag DECIMAL(10, 2), 
	info_rosinbag VARCHAR(100), 
	PRIMARY KEY (id_rosinbag), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "SuiviSolVivant" (
	id_suivi INTEGER NOT NULL, 
	nom_pot VARCHAR(200) NOT NULL, 
	id_materiel INTEGER, 
	id_recette_lso INTEGER, 
	volume_pot_l FLOAT, 
	date_preparation DATE, 
	commentaires TEXT, 
	PRIMARY KEY (id_suivi), 
	FOREIGN KEY(id_materiel) REFERENCES "Materiel" (id_materiel), 
	FOREIGN KEY(id_recette_lso) REFERENCES "RecetteLSO" (id_recette_lso)
)`,
`CREATE TABLE "VapoConsommable" (
	id_consommable INTEGER NOT NULL, 
	id_vaporisateur INTEGER, 
	type_consommable VARCHAR(100) NOT NULL, 
	diametre_mm FLOAT, 
	matiere VARCHAR(50), 
	date_achat DATE, 
	prix_achat DECIMAL(10, 2), 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_consommable), 
	FOREIGN KEY(id_vaporisateur) REFERENCES "Vaporisateur" (id_vaporisateur) ON DELETE SET NULL
)`,
`CREATE TABLE "Ventilation" (
	id_ventilation INTEGER NOT NULL, 
	id_fournisseur INTEGER, 
	id_marque INTEGER, 
	type_ventilation VARCHAR(50), 
	debit_ventilation INTEGER, 
	diametre_ventilation INTEGER, 
	longueur_ventilation INTEGER, 
	date_achat DATE, 
	prix DECIMAL(10, 2), 
	etat VARCHAR(50), 
	nbr_culture INTEGER, 
	PRIMARY KEY (id_ventilation), 
	FOREIGN KEY(id_fournisseur) REFERENCES "Fournisseur" (id_fournisseur), 
	FOREIGN KEY(id_marque) REFERENCES "Marque" (id_marque)
)`,
`CREATE TABLE "Croisement" (
	id_croisement INTEGER NOT NULL, 
	nom_croisement VARCHAR(255) NOT NULL, 
	type_croisement VARCHAR(20), 
	id_variete_mere INTEGER, 
	pheno_mere VARCHAR(100), 
	notes_mere TEXT, 
	id_pollen INTEGER, 
	id_variete_pere INTEGER, 
	pheno_pere VARCHAR(100), 
	pere_reverse BOOLEAN, 
	notes_pere TEXT, 
	date_pollinisation DATE, 
	methode VARCHAR(30), 
	zone_pollinisee VARCHAR(255), 
	quantite_pollen_utilisee_g DECIMAL(6, 3), 
	date_recolte_graines DATE, 
	nb_graines INTEGER, 
	qualite_graines VARCHAR(20), 
	poids_graines_g DECIMAL(6, 2), 
	id_variete_resultat INTEGER, 
	id_packgraine_resultat INTEGER, 
	statut VARCHAR(20), 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_croisement), 
	FOREIGN KEY(id_variete_mere) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_pollen) REFERENCES "Pollen" (id_pollen), 
	FOREIGN KEY(id_variete_pere) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_variete_resultat) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_packgraine_resultat) REFERENCES "PackGraine" (id_packgraine)
)`,
`CREATE TABLE "Culture" (
	id_culture INTEGER NOT NULL, 
	id_box INTEGER, 
	id_espace INTEGER, 
	nom VARCHAR(200), 
	date_debut DATE, 
	statut VARCHAR(50), 
	date_fin DATE, 
	date_recolte_estimee DATE, 
	type_culture VARCHAR(50), 
	type_eclairage VARCHAR(50), 
	but_culture VARCHAR(100), 
	date_germination DATE, 
	date_debut_croissance DATE, 
	date_passage_12_12 DATE, 
	date_debut_floraison DATE, 
	duree_croissance INTEGER, 
	duree_stretch INTEGER, 
	phase VARCHAR(50), 
	notes TEXT, 
	PRIMARY KEY (id_culture), 
	FOREIGN KEY(id_box) REFERENCES "Box" (id_box), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "EspaceMateriel" (
	id_espace_materiel INTEGER NOT NULL, 
	id_espace INTEGER NOT NULL, 
	id_materiel INTEGER NOT NULL, 
	date_assignation DATE, 
	notes VARCHAR(500), 
	PRIMARY KEY (id_espace_materiel), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace), 
	FOREIGN KEY(id_materiel) REFERENCES "Materiel" (id_materiel)
)`,
`CREATE TABLE "GoveeDevice" (
	id_device INTEGER NOT NULL, 
	nom VARCHAR(200) NOT NULL, 
	device_id VARCHAR(100), 
	modele VARCHAR(50), 
	ip_lan VARCHAR(50), 
	id_espace INTEGER, 
	actif BOOLEAN, 
	notes TEXT, 
	PRIMARY KEY (id_device), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "Graine" (
	id_graine INTEGER NOT NULL, 
	id_breeder INTEGER, 
	id_variete INTEGER, 
	id_packgraine INTEGER, 
	duree_flo_min INTEGER, 
	duree_flo_max INTEGER, 
	types_graines VARCHAR(50), 
	prix_achat DECIMAL(10, 2), 
	edition_limite BOOLEAN, 
	date_achat DATE, 
	utilisee BOOLEAN, 
	PRIMARY KEY (id_graine), 
	FOREIGN KEY(id_breeder) REFERENCES "Breeder" (id_breeder), 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_packgraine) REFERENCES "PackGraine" (id_packgraine)
)`,
`CREATE TABLE "HistoriqueCulture" (
	id_historique_culture INTEGER NOT NULL, 
	nom VARCHAR(200), 
	date_debut DATE, 
	date_fin DATE, 
	tente VARCHAR(100), 
	lampe VARCHAR(100), 
	puissance INTEGER, 
	type_culture VARCHAR(50), 
	engrais VARCHAR(100), 
	substrat VARCHAR(100), 
	id_espace INTEGER, 
	notes TEXT, 
	cout_engrais DECIMAL(10, 2), 
	cout_electricite DECIMAL(10, 2), 
	cout_graines DECIMAL(10, 2), 
	cout_total DECIMAL(10, 2), 
	cout_par_gramme DECIMAL(10, 4), 
	PRIMARY KEY (id_historique_culture), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "PlanCulture" (
	id_plan INTEGER NOT NULL, 
	nom VARCHAR(200) NOT NULL, 
	id_espace INTEGER, 
	statut VARCHAR(20), 
	notes TEXT, 
	created_at DATETIME, 
	updated_at DATETIME, 
	PRIMARY KEY (id_plan), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "SessionCuring" (
	id_session_curing INTEGER NOT NULL, 
	nom VARCHAR(200), 
	type_contenant VARCHAR(50), 
	volume_contenant_l DECIMAL(6, 2), 
	boveda_rh INTEGER, 
	id_espace INTEGER, 
	id_materiel_bocal INTEGER, 
	statut VARCHAR(50), 
	date_debut DATE, 
	date_fin DATE, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_session_curing), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace), 
	FOREIGN KEY(id_materiel_bocal) REFERENCES "Materiel" (id_materiel)
)`,
`CREATE TABLE "SessionSechage" (
	id_session_sechage INTEGER NOT NULL, 
	id_espace INTEGER, 
	nom VARCHAR(200), 
	methode_sechage VARCHAR(50), 
	temperature_cible FLOAT, 
	humidite_cible FLOAT, 
	statut VARCHAR(50), 
	date_debut DATE, 
	date_fin DATE, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_session_sechage), 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "SuiviArrosage" (
	id_suivi_arrosage INTEGER NOT NULL, 
	id_suivi INTEGER NOT NULL, 
	id_recette_engrais INTEGER, 
	volume_eau_l FLOAT, 
	date_application DATE, 
	notes TEXT, 
	PRIMARY KEY (id_suivi_arrosage), 
	FOREIGN KEY(id_suivi) REFERENCES "SuiviSolVivant" (id_suivi), 
	FOREIGN KEY(id_recette_engrais) REFERENCES "RecetteEngrais" (id_recette)
)`,
`CREATE TABLE "SuiviCulture" (
	id_suivi_culture INTEGER NOT NULL, 
	id_suivi INTEGER NOT NULL, 
	description VARCHAR(500), 
	date_debut DATE, 
	date_fin DATE, 
	notes TEXT, 
	PRIMARY KEY (id_suivi_culture), 
	FOREIGN KEY(id_suivi) REFERENCES "SuiviSolVivant" (id_suivi)
)`,
`CREATE TABLE "SuiviFermentation" (
	id_suivi_ferm INTEGER NOT NULL, 
	id_suivi INTEGER NOT NULL, 
	id_recette_ferm INTEGER, 
	volume_applique FLOAT, 
	date_application DATE, 
	notes TEXT, 
	PRIMARY KEY (id_suivi_ferm), 
	FOREIGN KEY(id_suivi) REFERENCES "SuiviSolVivant" (id_suivi), 
	FOREIGN KEY(id_recette_ferm) REFERENCES "RecetteFermentation" (id_recette_ferm)
)`,
`CREATE TABLE "SuiviReamendement" (
	id_suivi_reamend INTEGER NOT NULL, 
	id_suivi INTEGER NOT NULL, 
	id_recette_reamend INTEGER, 
	date_application DATE, 
	notes TEXT, 
	PRIMARY KEY (id_suivi_reamend), 
	FOREIGN KEY(id_suivi) REFERENCES "SuiviSolVivant" (id_suivi), 
	FOREIGN KEY(id_recette_reamend) REFERENCES "RecetteReamendement" (id_recette_reamend)
)`,
`CREATE TABLE "SuiviTCO" (
	id_suivi_tco INTEGER NOT NULL, 
	id_suivi INTEGER NOT NULL, 
	id_recette_tco INTEGER, 
	volume_applique FLOAT, 
	date_application DATE, 
	notes TEXT, 
	PRIMARY KEY (id_suivi_tco), 
	FOREIGN KEY(id_suivi) REFERENCES "SuiviSolVivant" (id_suivi), 
	FOREIGN KEY(id_recette_tco) REFERENCES "RecetteTCO" (id_recette_tco)
)`,
`CREATE TABLE "CultureEngrais" (
	id_culture INTEGER NOT NULL, 
	id_engrais INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_engrais), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_engrais) REFERENCES "Engrais" (id_engrais) ON DELETE CASCADE
)`,
`CREATE TABLE "CultureGraine" (
	id_culture INTEGER NOT NULL, 
	id_graine INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_graine), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_graine) REFERENCES "Graine" (id_graine) ON DELETE CASCADE
)`,
`CREATE TABLE "CultureIrrigation" (
	id_culture INTEGER NOT NULL, 
	id_irrigation INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_irrigation), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_irrigation) REFERENCES "Irrigation" (id_irrigation) ON DELETE CASCADE
)`,
`CREATE TABLE "CultureLampe" (
	id_culture INTEGER NOT NULL, 
	id_lampe INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_lampe), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_lampe) REFERENCES "Lampe" (id_lampe) ON DELETE CASCADE
)`,
`CREATE TABLE "CulturePot" (
	id_culture INTEGER NOT NULL, 
	id_pot INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_pot), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_pot) REFERENCES "Pot" (id_pot) ON DELETE CASCADE
)`,
`CREATE TABLE "CultureVentilation" (
	id_culture INTEGER NOT NULL, 
	id_ventilation INTEGER NOT NULL, 
	PRIMARY KEY (id_culture, id_ventilation), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_ventilation) REFERENCES "Ventilation" (id_ventilation) ON DELETE CASCADE
)`,
`CREATE TABLE "HistoriquePlant" (
	id_historique_plant INTEGER NOT NULL, 
	id_historique_culture INTEGER NOT NULL, 
	id_variete INTEGER, 
	variete_nom VARCHAR(255), 
	numero_plant INTEGER, 
	date_debut_plant DATE, 
	date_fin_plant DATE, 
	prix_graine DECIMAL(10, 2), 
	quantite_recoltee DECIMAL(10, 2), 
	notes TEXT, 
	PRIMARY KEY (id_historique_plant), 
	FOREIGN KEY(id_historique_culture) REFERENCES "HistoriqueCulture" (id_historique_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete)
)`,
`CREATE TABLE "PlanCultureVariete" (
	id_plan_variete INTEGER NOT NULL, 
	id_plan INTEGER NOT NULL, 
	id_packgraine INTEGER NOT NULL, 
	nb_plantes INTEGER NOT NULL, 
	taille_pot_l DECIMAL(6, 1), 
	ordre INTEGER, 
	PRIMARY KEY (id_plan_variete), 
	FOREIGN KEY(id_plan) REFERENCES "PlanCulture" (id_plan) ON DELETE CASCADE, 
	FOREIGN KEY(id_packgraine) REFERENCES "PackGraine" (id_packgraine)
)`,
`CREATE TABLE "Plant" (
	id_plant INTEGER NOT NULL, 
	id_culture INTEGER NOT NULL, 
	id_graine INTEGER, 
	nom_affichage VARCHAR(100) NOT NULL, 
	numero_plant INTEGER, 
	origine VARCHAR(7), 
	statut VARCHAR(50), 
	date_germination DATE, 
	date_debut_flo DATE, 
	date_recolte DATE, 
	date_fin_sechage DATE, 
	poids_recolte_g DECIMAL(10, 2), 
	substrat VARCHAR(100), 
	id_recette_sol INTEGER, 
	id_pot INTEGER, 
	volume_pot_l DECIMAL(6, 2), 
	notes TEXT, 
	id_plant_mere INTEGER, 
	date_prelevement DATE, 
	date_enracinement DATE, 
	statut_clone VARCHAR(20), 
	PRIMARY KEY (id_plant), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_graine) REFERENCES "Graine" (id_graine), 
	FOREIGN KEY(id_recette_sol) REFERENCES "RecetteLSO" (id_recette_lso), 
	FOREIGN KEY(id_plant_mere) REFERENCES "Plant" (id_plant) ON DELETE SET NULL
)`,
`CREATE TABLE "ProjetOpenField" (
	id_projet INTEGER NOT NULL, 
	nom VARCHAR(255) NOT NULL, 
	saison VARCHAR(50), 
	lieu VARCHAR(255), 
	conditions VARCHAR(50), 
	id_culture INTEGER, 
	statut VARCHAR(20), 
	description TEXT, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_projet), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE SET NULL
)`,
`CREATE TABLE "Recolte" (
	id_recolte INTEGER NOT NULL, 
	id_culture INTEGER, 
	date_recolte DATE, 
	quantite DECIMAL(10, 2), 
	PRIMARY KEY (id_recolte), 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture)
)`,
`CREATE TABLE "TemperatureLog" (
	id_log INTEGER NOT NULL, 
	id_device INTEGER, 
	id_culture INTEGER, 
	id_espace INTEGER, 
	date_heure DATETIME NOT NULL, 
	temperature FLOAT, 
	humidite FLOAT, 
	vpd FLOAT, 
	source VARCHAR(50), 
	PRIMARY KEY (id_log), 
	FOREIGN KEY(id_device) REFERENCES "GoveeDevice" (id_device) ON DELETE CASCADE, 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE, 
	FOREIGN KEY(id_espace) REFERENCES "EspaceCulture" (id_espace)
)`,
`CREATE TABLE "ActionCalendrier" (
	id_action INTEGER NOT NULL, 
	id_plant INTEGER, 
	id_culture INTEGER NOT NULL, 
	date_action DATE NOT NULL, 
	type_action VARCHAR(100) NOT NULL, 
	parametres JSON, 
	note TEXT, 
	global_culture BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id_action), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant) ON DELETE CASCADE, 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE
)`,
`CREATE TABLE "Photo" (
	id_photo INTEGER NOT NULL, 
	filename VARCHAR(255) NOT NULL, 
	filepath VARCHAR(500) NOT NULL, 
	thumbnail_path VARCHAR(500), 
	date_prise DATETIME NOT NULL, 
	notes TEXT, 
	id_plant INTEGER, 
	id_culture INTEGER, 
	taille_ko INTEGER, 
	largeur_px INTEGER, 
	hauteur_px INTEGER, 
	created_at DATETIME, 
	PRIMARY KEY (id_photo), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant) ON DELETE SET NULL, 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE SET NULL
)`,
`CREATE TABLE "PlantCuring" (
	id_plant_curing INTEGER NOT NULL, 
	id_plant INTEGER NOT NULL, 
	id_session_curing INTEGER NOT NULL, 
	date_mise_curing DATE, 
	date_fin_curing DATE, 
	poids_debut_g DECIMAL(10, 2), 
	poids_final_g DECIMAL(10, 2), 
	notes TEXT, 
	PRIMARY KEY (id_plant_curing), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant) ON DELETE CASCADE, 
	FOREIGN KEY(id_session_curing) REFERENCES "SessionCuring" (id_session_curing) ON DELETE CASCADE
)`,
`CREATE TABLE "PlantSechage" (
	id_plant_sechage INTEGER NOT NULL, 
	id_plant INTEGER NOT NULL, 
	id_session_sechage INTEGER NOT NULL, 
	date_mise_sechage DATE, 
	date_fin_sechage DATE, 
	poids_humide_g DECIMAL(10, 2), 
	poids_sec_g DECIMAL(10, 2), 
	notes TEXT, 
	PRIMARY KEY (id_plant_sechage), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant) ON DELETE CASCADE, 
	FOREIGN KEY(id_session_sechage) REFERENCES "SessionSechage" (id_session_sechage) ON DELETE CASCADE
)`,
`CREATE TABLE "PlanteMereOpenField" (
	id_mere INTEGER NOT NULL, 
	id_projet INTEGER NOT NULL, 
	id_variete INTEGER, 
	nom_phenotype VARCHAR(255), 
	id_plant INTEGER, 
	date_pollinisation DATE, 
	methode_pollinisation VARCHAR(30), 
	pere_identifie BOOLEAN, 
	id_pollen INTEGER, 
	nom_pere_libre VARCHAR(255), 
	id_peres JSON, 
	notes_pollinisation TEXT, 
	date_recolte DATE, 
	nb_graines INTEGER, 
	poids_graines_g DECIMAL(6, 2), 
	qualite_graines VARCHAR(20), 
	id_packgraine INTEGER, 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_mere), 
	FOREIGN KEY(id_projet) REFERENCES "ProjetOpenField" (id_projet) ON DELETE CASCADE, 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant) ON DELETE SET NULL, 
	FOREIGN KEY(id_pollen) REFERENCES "Pollen" (id_pollen) ON DELETE SET NULL, 
	FOREIGN KEY(id_packgraine) REFERENCES "PackGraine" (id_packgraine) ON DELETE SET NULL
)`,
`CREATE TABLE "PlantePereOpenField" (
	id_pere INTEGER NOT NULL, 
	id_projet INTEGER NOT NULL, 
	id_variete INTEGER, 
	nom_libre VARCHAR(255), 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id_pere), 
	FOREIGN KEY(id_projet) REFERENCES "ProjetOpenField" (id_projet) ON DELETE CASCADE, 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete)
)`,
`CREATE TABLE "RecolteCulture" (
	id_recolte INTEGER NOT NULL, 
	id_culture INTEGER NOT NULL, 
	PRIMARY KEY (id_recolte, id_culture), 
	FOREIGN KEY(id_recolte) REFERENCES "Recolte" (id_recolte) ON DELETE CASCADE, 
	FOREIGN KEY(id_culture) REFERENCES "Culture" (id_culture) ON DELETE CASCADE
)`,
`CREATE TABLE "RecolteGraine" (
	id_recolte INTEGER NOT NULL, 
	id_graine INTEGER NOT NULL, 
	PRIMARY KEY (id_recolte, id_graine), 
	FOREIGN KEY(id_recolte) REFERENCES "Recolte" (id_recolte) ON DELETE CASCADE, 
	FOREIGN KEY(id_graine) REFERENCES "Graine" (id_graine) ON DELETE CASCADE
)`,
`CREATE TABLE "Stock" (
	id_stock INTEGER NOT NULL, 
	id_variete INTEGER, 
	id_bocal INTEGER, 
	id_materiel_bocal INTEGER, 
	id_plant INTEGER, 
	type_stock VARCHAR(50), 
	sous_type_stock VARCHAR(50), 
	lampe_type VARCHAR(50), 
	engrais_type VARCHAR(200), 
	substrat_type VARCHAR(200), 
	maillage VARCHAR(20), 
	type_hash VARCHAR(50), 
	type_rosin VARCHAR(50), 
	date_stock DATE, 
	date_fin_stock DATE, 
	quantite_stock DECIMAL(10, 2), 
	quantite_initiale DECIMAL(10, 2), 
	PRIMARY KEY (id_stock), 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_bocal) REFERENCES "Bocal" (id_bocal), 
	FOREIGN KEY(id_materiel_bocal) REFERENCES "Materiel" (id_materiel), 
	FOREIGN KEY(id_plant) REFERENCES "Plant" (id_plant)
)`,
`CREATE TABLE "HashExtraction" (
	id_hashextraction INTEGER NOT NULL, 
	id_variete INTEGER, 
	id_iceobag INTEGER, 
	id_stock_source INTEGER, 
	nom_variete_hash VARCHAR(100), 
	date_hashextraction DATE, 
	type_extraction VARCHAR(20), 
	duree_polinator INTEGER, 
	maillage_polinator VARCHAR(20), 
	passages JSON, 
	sacs JSON, 
	sources JSON, 
	quantite_utilisee DECIMAL(10, 2), 
	quantite_extraite DECIMAL(10, 2), 
	info_hashextraction TEXT, 
	PRIMARY KEY (id_hashextraction), 
	FOREIGN KEY(id_variete) REFERENCES "Variete" (id_variete), 
	FOREIGN KEY(id_iceobag) REFERENCES "IceOBag" (id_iceobag), 
	FOREIGN KEY(id_stock_source) REFERENCES "Stock" (id_stock)
)`,
`CREATE TABLE "RosinExtraction" (
	id_rosinextraction INTEGER NOT NULL, 
	id_bocal INTEGER, 
	id_rosinbag INTEGER, 
	id_press INTEGER, 
	id_stock_source INTEGER, 
	id_stock_produit INTEGER, 
	nom_variete_extract VARCHAR(50), 
	date_rosinextraction DATE, 
	temperature_extraction INTEGER, 
	maillage VARCHAR(20), 
	duree_preheat INTEGER, 
	duree_extraction INTEGER, 
	sac_1_poids DECIMAL(10, 2), 
	sac_2_poids DECIMAL(10, 2), 
	sac_3_poids DECIMAL(10, 2), 
	sac_4_poids DECIMAL(10, 2), 
	sources JSON, 
	quantite_utilisee DECIMAL(10, 2), 
	presse_1_poids DECIMAL(10, 2), 
	presse_2_poids DECIMAL(10, 2), 
	presse_3_poids DECIMAL(10, 2), 
	presse_4_poids DECIMAL(10, 2), 
	quantite_extraite DECIMAL(10, 2), 
	info_rosinextraction VARCHAR(255), 
	PRIMARY KEY (id_rosinextraction), 
	FOREIGN KEY(id_bocal) REFERENCES "Bocal" (id_bocal), 
	FOREIGN KEY(id_rosinbag) REFERENCES "RosinBag" (id_rosinbag), 
	FOREIGN KEY(id_press) REFERENCES "Press" (id_press), 
	FOREIGN KEY(id_stock_source) REFERENCES "Stock" (id_stock), 
	FOREIGN KEY(id_stock_produit) REFERENCES "Stock" (id_stock)
)`,
`CREATE TABLE "SessionConsommation" (
	id_session INTEGER NOT NULL, 
	date_heure DATETIME NOT NULL, 
	id_vaporisateur INTEGER, 
	type_produit VARCHAR(20) NOT NULL, 
	id_stock INTEGER, 
	quantite_g DECIMAL(6, 3) NOT NULL, 
	options_vapo JSON, 
	notes TEXT, 
	PRIMARY KEY (id_session), 
	FOREIGN KEY(id_vaporisateur) REFERENCES "Vaporisateur" (id_vaporisateur) ON DELETE SET NULL, 
	FOREIGN KEY(id_stock) REFERENCES "Stock" (id_stock) ON DELETE SET NULL
)`,
]
