-- Tables de référence
CREATE TABLE Marque (id_marque INT AUTO_INCREMENT PRIMARY KEY, nom_marque VARCHAR(50), siteweb_marque VARCHAR(100), contact_marque VARCHAR(100));
CREATE TABLE Fournisseur (id_fournisseur INT AUTO_INCREMENT PRIMARY KEY, nom_fournisseur VARCHAR(255) NOT NULL, site_web VARCHAR(255));
CREATE TABLE Breeder (id_breeder INT AUTO_INCREMENT PRIMARY KEY, nom_breeder VARCHAR(255) NOT NULL, origine_breeder VARCHAR(255), information_breeder VARCHAR(255));
CREATE TABLE Variete (id_variete INT AUTO_INCREMENT PRIMARY KEY, nom_variete VARCHAR(255) NOT NULL, croisement_variete VARCHAR(255), informations_variete VARCHAR(255));

-- Graines
CREATE TABLE PackGraine (id_packgraine INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, nbr_graines INT, prix_achat DECIMAL(10,2), date_achat DATE, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur));
CREATE TABLE Graine (id_graine INT AUTO_INCREMENT PRIMARY KEY, id_breeder INT, id_variete INT, id_packgraine INT, duree_flo_min INT, duree_flo_max INT, types_graines VARCHAR(50), prix_achat DECIMAL(10,2), edition_limite TINYINT(1) DEFAULT 0, date_achat DATE, utilisee TINYINT(1) DEFAULT 0, FOREIGN KEY (id_breeder) REFERENCES Breeder(id_breeder), FOREIGN KEY (id_variete) REFERENCES Variete(id_variete), FOREIGN KEY (id_packgraine) REFERENCES PackGraine(id_packgraine));

-- Matériel
CREATE TABLE Box (id_box INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, largeur_tente INT, profondeur_tente INT, hauteur_tente INT, nbr_etage INT, date_achat DATE, prix DECIMAL(10,2), etat VARCHAR(50), nbr_culture INT DEFAULT 0, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Lampe (id_lampe INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, largeur_lampe INT, profondeur_lampe INT, hauteur_lampe INT, puissance_lampe INT, date_achat DATE, prix DECIMAL(10,2), etat VARCHAR(50), nbr_culture INT DEFAULT 0, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Pot (id_pot INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, taille_pot INT, dimension_pot VARCHAR(50), date_achat DATE, prix DECIMAL(10,2), etat VARCHAR(50), nbr_culture INT DEFAULT 0, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Irrigation (id_irrigation INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, type_irrigation VARCHAR(50), debit_irrigation INT, diametre_irrigation INT, date_achat DATE, prix DECIMAL(10,2), nbr_culture INT DEFAULT 0, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Ventilation (id_ventilation INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, type_ventilation VARCHAR(50), debit_ventilation INT, diametre_ventilation INT, longueur_ventilation INT, date_achat DATE, prix DECIMAL(10,2), etat VARCHAR(50), nbr_culture INT DEFAULT 0, FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Bocal (id_bocal INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, taille_bocal INT, date_achat DATE, prix DECIMAL(10,2), FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Press (id_press INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, largeur_plate DECIMAL(10,1), profondeur_plate DECIMAL(10,1), pression_press INT, date_achat DATE, prix DECIMAL(10,2), FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE RosinBag (id_rosinbag INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, dimensions_rosinbag VARCHAR(50), maillage VARCHAR(50), nombre_rosinbag VARCHAR(50), date_achat_rosinbag DATE, prix_rosinbag DECIMAL(10,2), info_rosinbag VARCHAR(100), FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE IceOBag (id_iceobag INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, maillage_iceobag VARCHAR(50), date_achat_iceobag DATE, prix_iceobag DECIMAL(10,2), info_iceobag VARCHAR(100), FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));
CREATE TABLE Engrais (id_engrais INT AUTO_INCREMENT PRIMARY KEY, id_fournisseur INT, id_marque INT, nom_engrais VARCHAR(255), quantite_bouteille DECIMAL(10,2), quantite_restante DECIMAL(10,2), unite_mesure VARCHAR(10), prix_achat DECIMAL(10,2), date_achat DATE, date_peremption DATE, information_complementaire VARCHAR(255), FOREIGN KEY (id_fournisseur) REFERENCES Fournisseur(id_fournisseur), FOREIGN KEY (id_marque) REFERENCES Marque(id_marque));

-- Culture
CREATE TABLE Culture (id_culture INT AUTO_INCREMENT PRIMARY KEY, id_box INT, type_culture VARCHAR(50), date_germination DATE, date_debut_croissance DATE, date_passage_12_12 DATE, date_debut_floraison DATE, duree_croissance INT, duree_stretch INT, phase VARCHAR(50), notes TEXT, FOREIGN KEY (id_box) REFERENCES Box(id_box));
CREATE TABLE CultureGraine (id_culture INT, id_graine INT, PRIMARY KEY (id_culture, id_graine), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_graine) REFERENCES Graine(id_graine) ON DELETE CASCADE);
CREATE TABLE CultureEngrais (id_culture INT, id_engrais INT, PRIMARY KEY (id_culture, id_engrais), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_engrais) REFERENCES Engrais(id_engrais) ON DELETE CASCADE);
CREATE TABLE CultureLampe (id_culture INT, id_lampe INT, PRIMARY KEY (id_culture, id_lampe), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_lampe) REFERENCES Lampe(id_lampe) ON DELETE CASCADE);
CREATE TABLE CulturePot (id_culture INT, id_pot INT, PRIMARY KEY (id_culture, id_pot), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_pot) REFERENCES Pot(id_pot) ON DELETE CASCADE);
CREATE TABLE CultureIrrigation (id_culture INT, id_irrigation INT, PRIMARY KEY (id_culture, id_irrigation), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_irrigation) REFERENCES Irrigation(id_irrigation) ON DELETE CASCADE);
CREATE TABLE CultureVentilation (id_culture INT, id_ventilation INT, PRIMARY KEY (id_culture, id_ventilation), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_ventilation) REFERENCES Ventilation(id_ventilation) ON DELETE CASCADE);

-- Plants
CREATE TABLE Plant (id_plant INT AUTO_INCREMENT PRIMARY KEY, id_culture INT NOT NULL, id_graine INT, nom_affichage VARCHAR(100) NOT NULL, numero_plant INT, origine ENUM('graine','bouture','clone') DEFAULT 'graine', statut ENUM('germination','veg','floraison','sechage','recolte','abandonne') DEFAULT 'germination', date_germination DATE, date_debut_flo DATE, date_recolte DATE, date_fin_sechage DATE, poids_recolte_g DECIMAL(10,2), notes TEXT, FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE, FOREIGN KEY (id_graine) REFERENCES Graine(id_graine));
CREATE TABLE ActionCalendrier (id_action INT AUTO_INCREMENT PRIMARY KEY, id_plant INT, id_culture INT NOT NULL, date_action DATE NOT NULL, type_action ENUM('arrosage','nutrition','LST','defoliation','recolte','observation','autre') NOT NULL, note TEXT, global_culture TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (id_plant) REFERENCES Plant(id_plant) ON DELETE CASCADE, FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE);

-- Récolte
CREATE TABLE Recolte (id_recolte INT AUTO_INCREMENT PRIMARY KEY, id_culture INT, date_recolte DATE, quantite DECIMAL(10,2), FOREIGN KEY (id_culture) REFERENCES Culture(id_culture));
CREATE TABLE RecolteCulture (id_recolte INT, id_culture INT, PRIMARY KEY (id_recolte, id_culture), FOREIGN KEY (id_recolte) REFERENCES Recolte(id_recolte) ON DELETE CASCADE, FOREIGN KEY (id_culture) REFERENCES Culture(id_culture) ON DELETE CASCADE);
CREATE TABLE RecolteGraine (id_recolte INT, id_graine INT, PRIMARY KEY (id_recolte, id_graine), FOREIGN KEY (id_recolte) REFERENCES Recolte(id_recolte) ON DELETE CASCADE, FOREIGN KEY (id_graine) REFERENCES Graine(id_graine) ON DELETE CASCADE);

-- Stock
CREATE TABLE Stock (id_stock INT AUTO_INCREMENT PRIMARY KEY, id_variete INT, id_bocal INT, type_stock VARCHAR(50), sous_type_stock VARCHAR(50), date_stock DATE, quantite_stock DECIMAL(10,2), FOREIGN KEY (id_variete) REFERENCES Variete(id_variete), FOREIGN KEY (id_bocal) REFERENCES Bocal(id_bocal));

-- Extractions
CREATE TABLE RosinExtraction (id_rosinextraction INT AUTO_INCREMENT PRIMARY KEY, id_bocal INT, id_rosinbag INT, id_press INT, id_stock_source INT, nom_variete_extract VARCHAR(50), temperature_extraction INT, duree_preheat INT, duree_extraction INT, date_rosinextraction DATE, quantite_utilisee DECIMAL(10,2), quantite_extraite DECIMAL(10,2), info_rosinextraction VARCHAR(255), FOREIGN KEY (id_bocal) REFERENCES Bocal(id_bocal), FOREIGN KEY (id_rosinbag) REFERENCES RosinBag(id_rosinbag), FOREIGN KEY (id_press) REFERENCES Press(id_press), FOREIGN KEY (id_stock_source) REFERENCES Stock(id_stock));
CREATE TABLE HashExtraction (id_hashextraction INT AUTO_INCREMENT PRIMARY KEY, id_variete INT, id_iceobag INT, nom_variete_hash VARCHAR(50), date_hashextraction DATE, quantite_utilisee DECIMAL(10,2), quantite_extraite DECIMAL(10,2), info_hashextraction VARCHAR(100), FOREIGN KEY (id_variete) REFERENCES Variete(id_variete), FOREIGN KEY (id_iceobag) REFERENCES IceOBag(id_iceobag));
